# Generated by Django 5.1.6 on 2025-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("catering", "Catering"),
                            ("educational", "Education"),
                            ("cleaning", "Cleaning"),
                            ("tech", "Tech"),
                            ("recreational", "Recreational"),
                            ("outdoor", "Outdoor"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "hours_offered",
                    models.DecimalField(decimal_places=1, default=1, max_digits=4),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
