# Generated by Django 5.1.7 on 2025-03-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timebank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_credits',
            field=models.DecimalField(decimal_places=0, default=10, max_digits=8),
        ),
    ]
